__author__ = 'DWA'

margin=10
frameHeight=1000
frameWidth=1450
tmHeight=frameHeight-4*margin
tmWidth=tmHeight
mmHeight=360
mmWidth=mmHeight

tacMapWH=11 #MUST BE ODD
maxTacMapRadius=tacMapWH//2
tSize=tmWidth//(tacMapWH+1)

BLACK=(0,0,0)           # BEDROCK WALL (IMPENETRABLE)/UNUSED CONNECTORS/TAC MAP OUT-OF-BOUNDS TILES/MINI MAP UNVISITED TILES
BLUE=(0,0,70)           # TAC- and MINI-MAP BACKGROUND/TAC MAP UNUSED CONNECTORS (NOT DRAWN)
BROWN=(150,75,0)        # HALLS/UNFOUND STASHES/UNFOUND HALL CONTINUATIONS
DARKBROWN=(75,38,0)     # NORMAL DOORS
GRAY=(150,150,150)      # MINI-MAP ROOM
DARKGRAY=(15,15,15)     # OFF MAP AREA/DOOR FRAMES/TAC MAP SECRET DOOR "HINT"
GREEN=(0,100,0)         # MINI MAP SECRET DOORS (AFTER DISCOVERY)
ORANGE=(250,150,25)     # HALL OBSTRUCTION (AFTER DISCOVERY)
RED=(200,0,0)           # SECRET STASH/TRAP! (AFTER DISCOVERY)
WHITE=(255,255,255)     # FRAME BACKGROUND/MINI MAP PLAYER ICON

delay = 200
interval = 100